# This rule is not used by the project node-maintenance-orchestrator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to maintenance.nmoo.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: node-maintenance-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: nodemaintenanceplan-viewer-role
rules:
- apiGroups:
  - maintenance.nmoo.io
  resources:
  - nodemaintenanceplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maintenance.nmoo.io
  resources:
  - nodemaintenanceplans/status
  verbs:
  - get
