{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nmo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nmo.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nmo.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      scheme: http
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
